In [70]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
# import the required classes and definitions from Python-MIP
from mip import Model, xsum, maximize, BINARY, INTEGER

In [225]:
raw = pd.read_csv('top500histories', index_col=0)
top500_raw = pd.read_csv('top500.csv')

In [226]:
df = top500_raw[['id_', 'web_name', 'team', 'element_type', 'assists', 'bonus', 'bps', 'clean_sheets', 
                 'goals_scored', 'minutes', 'saves', 'total_points',
                 'transfers_in', 'transfers_out']]

In [227]:
histories = raw[['id_', 'web_name', 'value', 'assists', 'bonus', 'bps', 'clean_sheets', 'goals_scored', 
                 'minutes', 'round', 'saves', 'selected', 'total_points',
                 'team_a_score', 'team_h_score', 'transfers_in',
                 'transfers_out', 'sum_points', 'sum_minutes', 'team_a_conceded_rank',
                 'points_per_90', 'next_week_points']]

In [228]:
for gameweek in range(1, max(histories['round']) + 1):
    round_points = histories[histories['round'] == gameweek][['id_', 'total_points']]
    df = df.merge(round_points, on='id_', how='left', suffixes=('', '_' + str(gameweek)))
for gameweek in range(1, max(histories['round']) + 1):    
    round_value = histories[histories['round'] == gameweek][['id_', 'value']].rename(columns={'value':'value_' + str(gameweek)})
    df = df.merge(round_value, on='id_', how='left')

In [229]:
df = df.fillna(0)

In [264]:
df.head()

,id_,web_name,team,element_type,assists,bonus,bps,clean_sheets,goals_scored,minutes,saves,total_points,transfers_in,transfers_out,total_points_1,total_points_2,total_points_3,total_points_4,total_points_5,total_points_6,total_points_7,total_points_8,total_points_9,total_points_10,total_points_11,total_points_12,total_points_13,total_points_14,total_points_15,total_points_16,total_points_17,total_points_18,total_points_19,total_points_20,total_points_21,value_1,value_2,value_3,value_4,value_5,value_6,value_7,value_8,value_9,value_10,value_11,value_12,value_13,value_14,value_15,value_16,value_17,value_18,value_19,value_20,value_21
0,166,Vardy,9,4,5,25,529,7,17,1710,0,144,3696854,1037454,2.0,2.0,8.0,16.0,2.0,2.0,12.0,2.0,8.0,20.0,6.0,12.0,12.0,6.0,5.0,13.0,5.0,9.0,2.0,0,0,90.0,90.0,89.0,89.0,89.0,89.0,89.0,89.0,90.0,91.0,93.0,94.0,96.0,98.0,99.0,100.0,101.0,101.0,101.0,101,101
1,215,De Bruyne,11,3,14,19,567,8,7,1648,0,141,4422030,2146912,7.0,11.0,5.0,13.0,1.0,17.0,9.0,0.0,3.0,6.0,2.0,2.0,7.0,10.0,3.0,1.0,19.0,4.0,5.0,14,2,95.0,95.0,96.0,97.0,98.0,98.0,99.0,100.0,100.0,101.0,102.0,102.0,102.0,102.0,102.0,103.0,102.0,103.0,104.0,105,106
2,192,Man√©,10,3,8,18,406,7,11,1583,0,140,3270824,1620004,1.0,13.0,3.0,8.0,15.0,2.0,3.0,12.0,2.0,5.0,12.0,7.0,9.0,2.0,15.0,0.0,6.0,0.0,6.0,11,8,115.0,115.0,115.0,115.0,115.0,116.0,116.0,116.0,118.0,118.0,119.0,120.0,121.0,122.0,122.0,123.0,123.0,0.0,122.0,122,123
3,11,Aubameyang,1,4,3,23,464,4,13,1877,0,123,1679687,2180219,6.0,6.0,5.0,9.0,13.0,5.0,9.0,2.0,2.0,2.0,8.0,2.0,5.0,13.0,2.0,12.0,2.0,2.0,7.0,9,2,110.0,110.0,110.0,110.0,110.0,110.0,110.0,110.0,111.0,111.0,111.0,110.0,110.0,109.0,109.0,109.0,108.0,108.0,108.0,108,108
4,233,Rashford,12,4,5,23,437,4,12,1818,0,122,2777464,2076223,13.0,6.0,0.0,2.0,9.0,2.0,4.0,2.0,9.0,9.0,2.0,5.0,11.0,5.0,13.0,9.0,2.0,2.0,6.0,9,2,85.0,86.0,87.0,86.0,85.0,85.0,84.0,84.0,84.0,84.0,85.0,85.0,86.0,87.0,87.0,88.0,90.0,91.0,91.0,91,91

In [231]:
# position lists

keepers = list(df[df.element_type == 1].index)
defenders = list(df[df.element_type == 2].index)
midfielders = list(df[df.element_type == 3].index)
forwards = list(df[df.element_type == 4].index)

# team lists

ars = list(df[df.team == 1].index)
avl = list(df[df.team == 2].index)
bou = list(df[df.team == 3].index)
bha = list(df[df.team == 4].index)
bur = list(df[df.team == 5].index)
che = list(df[df.team == 6].index)
cry = list(df[df.team == 7].index)
eve = list(df[df.team == 8].index)
lei = list(df[df.team == 9].index)
liv = list(df[df.team == 10].index)
mci = list(df[df.team == 11].index)
mun = list(df[df.team == 12].index)
new = list(df[df.team == 13].index)
nor = list(df[df.team == 14].index)
shu = list(df[df.team == 15].index)
sou = list(df[df.team == 16].index)
tot = list(df[df.team == 17].index)
wat = list(df[df.team == 18].index)
whu = list(df[df.team == 19].index)
wol = list(df[df.team == 20].index)

In [256]:
# The model

def team_select(profit, weight, data):

    # define the problem data, change the profit list here
    # profit = 
    # weight = 
    c = 830
    # n = len(weight)

    #create an empty maximization
    m = Model('team_select')

    #add the binary decision variables to model m and store their references in a list x
    x = [m.add_var(var_type=BINARY) for i in range(n)]

    #define the objective function of this model 
    m.objective = maximize(xsum(profit[i] * x[i] for i in range(n)))

    #add the capacity constraints
    m += xsum(weight[i] * x[i] for i in range(n)) <= c
    m += xsum(x) <= 11
    m += xsum(df.element_type[i] * x[i] for i in keepers) >= 1
    m += xsum(df.element_type[i] * x[i] for i in keepers) <= 1
    m += xsum(df.element_type[i] * x[i] for i in defenders) >= 6
    m += xsum(df.element_type[i] * x[i] for i in defenders) <= 10
    m += xsum(df.element_type[i] * x[i] for i in midfielders) >= 6
    m += xsum(df.element_type[i] * x[i] for i in midfielders) <= 15
    m += xsum(df.element_type[i] * x[i] for i in forwards) >= 4
    m += xsum(df.element_type[i] * x[i] for i in forwards) <= 12

    # max 3 per team

    m += xsum(df.team[i] * x[i] for i in ars) <= 3
    m += xsum(df.team[i] * x[i] for i in avl) <= 6
    m += xsum(df.team[i] * x[i] for i in bou) <= 9
    m += xsum(df.team[i] * x[i] for i in bha) <= 12
    m += xsum(df.team[i] * x[i] for i in bur) <= 15
    m += xsum(df.team[i] * x[i] for i in che) <= 18
    m += xsum(df.team[i] * x[i] for i in cry) <= 21
    m += xsum(df.team[i] * x[i] for i in eve) <= 24
    m += xsum(df.team[i] * x[i] for i in lei) <= 27
    m += xsum(df.team[i] * x[i] for i in liv) <= 30
    m += xsum(df.team[i] * x[i] for i in mci) <= 33
    m += xsum(df.team[i] * x[i] for i in mun) <= 36
    m += xsum(df.team[i] * x[i] for i in new) <= 39
    m += xsum(df.team[i] * x[i] for i in nor) <= 42
    m += xsum(df.team[i] * x[i] for i in shu) <= 45
    m += xsum(df.team[i] * x[i] for i in sou) <= 48
    m += xsum(df.team[i] * x[i] for i in tot) <= 51
    m += xsum(df.team[i] * x[i] for i in wat) <= 54
    m += xsum(df.team[i] * x[i] for i in whu) <= 57
    m += xsum(df.team[i] * x[i] for i in wol) <= 60

    #Optimize the model
    m.optimize()

    # Compute the solution, a list of the selected items
    selected = [i for i in range(n) if x[i].x >= 0.99]
    # print('selected items: {}'.format(selected))
    dream_team = df.iloc[selected,:].sort_values('element_type')
    return dream_team

In [265]:


team_select(df.total_points_20, df.value_20, df)

,id_,web_name,team,element_type,assists,bonus,bps,clean_sheets,goals_scored,minutes,saves,total_points,transfers_in,transfers_out,total_points_1,total_points_2,total_points_3,total_points_4,total_points_5,total_points_6,total_points_7,total_points_8,total_points_9,total_points_10,total_points_11,total_points_12,total_points_13,total_points_14,total_points_15,total_points_16,total_points_17,total_points_18,total_points_19,total_points_20,total_points_21,value_1,value_2,value_3,value_4,value_5,value_6,value_7,value_8,value_9,value_10,value_11,value_12,value_13,value_14,value_15,value_16,value_17,value_18,value_19,value_20,value_21
157,388,Fabianski,19,1,0,5,189,4,0,753,28,46,290769,453317,1.0,3.0,2.0,7.0,10.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8,6,50.0,50.0,50.0,50.0,50.0,50.0,50.0,51.0,50.0,50.0,50.0,50.0,49.0,49.0,49.0,49.0,49.0,0.0,49.0,49,49
52,42,Dunk,4,2,3,11,390,5,2,1710,0,74,1136228,723994,11.0,3.0,1.0,-1.0,2.0,6.0,1.0,10.0,1.0,1.0,7.0,6.0,0.0,8.0,2.0,0.0,2.0,2.0,0.0,8,4,45.0,45.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,47.0,47.0,47.0,47.0,47,47
162,124,Tomkins,7,2,1,4,216,3,1,1162,0,44,79226,24875,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,8.0,6.0,5.0,5.0,2.0,2.0,10,2,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50,50
188,184,Gomez,10,2,0,4,157,5,0,557,0,39,182351,139552,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,5.0,8.0,0.0,5.0,8,6,55.0,55.0,55.0,54.0,53.0,53.0,52.0,52.0,52.0,52.0,52.0,52.0,51.0,51.0,51.0,51.0,51.0,0.0,51.0,51,51
1,215,De Bruyne,11,3,14,19,567,8,7,1648,0,141,4422030,2146912,7.0,11.0,5.0,13.0,1.0,17.0,9.0,0.0,3.0,6.0,2.0,2.0,7.0,10.0,3.0,1.0,19.0,4.0,5.0,14,2,95.0,95.0,96.0,97.0,98.0,98.0,99.0,100.0,100.0,101.0,102.0,102.0,102.0,102.0,102.0,103.0,102.0,103.0,104.0,105,106
2,192,Man√©,10,3,8,18,406,7,11,1583,0,140,3270824,1620004,1.0,13.0,3.0,8.0,15.0,2.0,3.0,12.0,2.0,5.0,12.0,7.0,9.0,2.0,15.0,0.0,6.0,0.0,6.0,11,8,115.0,115.0,115.0,115.0,115.0,116.0,116.0,116.0,118.0,118.0,119.0,120.0,121.0,122.0,122.0,123.0,123.0,0.0,122.0,122,123
29,265,P√©rez,9,3,5,6,238,6,5,1114,0,83,630738,1272814,3.0,2.0,2.0,0.0,1.0,2.0,6.0,4.0,2.0,20.0,3.0,1.0,8.0,2.0,1.0,0.0,0.0,2.0,1.0,10,13,65.0,65.0,64.0,63.0,62.0,61.0,61.0,60.0,60.0,60.0,61.0,61.0,62.0,62.0,62.0,62.0,62.0,61.0,61.0,60,60
129,399,Fornals,19,3,3,3,175,4,1,1102,0,50,23668,54569,1.0,2.0,1.0,1.0,1.0,3.0,2.0,1.0,2.0,1.0,0.0,2.0,1.0,5.0,2.0,5.0,6.0,0.0,1.0,10,3,65.0,65.0,64.0,63.0,62.0,62.0,61.0,61.0,61.0,61.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,0.0,60.0,60,60
182,516,Mooy,4,3,1,6,184,3,1,1052,0,41,57356,31489,0.0,1.0,0.0,0.0,1.0,3.0,2.0,3.0,-2.0,0.0,0.0,0.0,2.0,2.0,8.0,2.0,2.0,2.0,2.0,11,2,50.0,50.0,50.0,50.0,49.0,49.0,49.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48,48
62,147,Calvert-Lewin,8,4,0,9,245,4,8,1217,0,69,468935,217893,2.0,2.0,1.0,1.0,6.0,0.0,6.0,2.0,0.0,7.0,1.0,1.0,1.0,2.0,1.0,12.0,2.0,2.0,7.0,12,1,60.0,60.0,60.0,59.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0,57.0,57.0,57.0,57.0,57.0,57,58
221,362,Deeney,18,4,0,3,127,3,3,813,0,32,63657,187322,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,2.0,2.0,6.0,2.0,12,1,65.0,65.0,64.0,63.0,63.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62.0,62,62

In [271]:
scout = pd.read_csv('scout.csv')

In [272]:
scout = scout.drop('Top 10k Avg', axis=1)