In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('top500histories.csv', index_col=0)
df.columns

Index(['assists', 'bonus', 'bps', 'clean_sheets', 'creativity', 'element',
       'fixture', 'goals_conceded', 'goals_scored', 'ict_index', 'influence',
       'kickoff_time', 'minutes', 'opponent_team', 'own_goals',
       'penalties_missed', 'penalties_saved', 'red_cards', 'round', 'saves',
       'selected', 'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'id_'],
      dtype='object')

In [7]:
df_totals = pd.read_csv('top500.csv', index_col=0)
df_totals

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,...,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
id,,,,,,,,,,,,,,,,,,,,,
215,9,10,246,75.0,0.0,3,61366,0,0,5,...,168.0,63,2191000,98273,1321505,155038,0.7,6.3,De Bruyne,0
210,3,6,255,NaN,NaN,2,37572,0,0,2,...,392.0,61,1186805,45823,518527,49181,0.4,5.0,Agüero,0
192,2,8,162,100.0,100.0,3,110979,1,-1,2,...,260.0,57,1401900,362810,637616,12568,0.7,4.9,Mané,0
191,3,7,150,75.0,NaN,3,118748,0,0,0,...,464.0,55,838413,10349,1276908,363221,0.4,4.4,Salah,0
11,1,10,215,NaN,NaN,2,54694,1,-1,1,...,384.0,55,950071,138152,856519,28407,0.7,5.0,Aubameyang,2
460,0,11,201,100.0,100.0,1,173879,1,-1,7,...,332.0,54,2962521,253732,367606,17102,0.9,7.1,Abraham,2
278,2,9,208,NaN,NaN,0,57127,-1,1,6,...,397.0,54,3174376,20866,1034372,388276,0.6,7.5,Pukki,1
214,0,4,167,NaN,NaN,2,103955,0,0,1,...,491.0,48,1311234,62197,976464,79223,0.2,4.0,Sterling,2
187,4,9,195,NaN,NaN,3,92217,0,0,1,...,407.0,48,603026,26981,499632,48776,0.5,5.0,Firmino,0
67,3,4,173,NaN,NaN,0,75115,0,0,-1,...,275.0,48,514888,113129,790116,25427,0.9,6.1,Callum Wilson,1
338,1,7,163,NaN,NaN,1,78830,-1,1,-1,...,279.0,46,692224,19687,1345934,91733,0.5,4.2,Kane,0
217,5,6,170,NaN,NaN,3,103025,1,-1,2,...,224.0,46,734858,69173,303816,62790,0.8,5.3,Mahrez,0
166,1,8,143,NaN,NaN,2,101668,1,-1,0,...,209.0,46,533808,121479,514661,21145,0.5,5.2,Vardy,1
463,1,6,164,100.0,100.0,1,184341,1,-1,8,...,232.0,46,2779792,242338,584452,16814,0.9,6.9,Mount,0
219,5,3,137,NaN,NaN,4,20664,0,0,1,...,204.0,40,742039,35840,395172,39865,0.5,5.3,David Silva,0
428,1,7,124,NaN,NaN,2,213345,1,-1,1,...,321.0,40,257202,73142,152492,8800,1.0,6.7,Wesley,0
182,3,3,197,NaN,NaN,2,169187,0,0,2,...,124.0,40,904411,59669,473130,24434,0.6,5.6,Alexander-Arnold,2
159,0,5,154,NaN,NaN,2,111931,1,-1,2,...,51.0,40,493009,174541,183295,12907,1.0,6.6,Pereira,0
297,1,7,155,NaN,NaN,3,153723,0,0,5,...,91.0,39,1777901,94828,223345,13155,1.2,8.7,Lundstram,3
123,0,3,138,NaN,NaN,3,74230,0,0,1,...,78.0,39,620436,53872,302356,16341,0.7,7.0,van Aanholt,0
31,1,4,141,NaN,NaN,2,122806,0,0,3,...,203.0,39,937468,90275,310860,30061,0.9,6.7,McGinn,1
68,3,5,115,NaN,NaN,0,78007,0,0,-2,...,155.0,38,402965,60304,1013298,28484,1.0,6.0,King,0
233,2,7,132,100.0,100.0,2,176297,0,0,-1,...,280.0,38,831365,5390,1457676,38764,0.5,4.5,Rashford,1
411,0,4,155,NaN,NaN,3,38533,0,0,1,...,0.0,38,543030,122359,225548,8934,0.9,7.5,Patrício,0
457,1,5,146,100.0,100.0,3,103123,0,0,-1,...,387.0,37,465993,19738,402819,19541,0.5,5.0,Haller,1
342,3,3,111,100.0,100.0,1,85971,0,0,3,...,242.0,35,954457,51252,269588,79376,0.7,3.6,Son,0
47,0,6,176,NaN,NaN,3,131897,0,0,1,...,0.0,35,467314,103256,342988,9291,1.3,7.6,Ryan,0
218,1,2,145,NaN,NaN,1,165809,0,0,-1,...,320.0,35,548513,47114,1201348,62440,0.8,4.4,Bernardo Silva,2
171,2,4,110,100.0,100.0,1,172780,1,-1,2,...,190.0,34,677856,156426,509220,24983,0.6,4.8,Maddison,1
447,3,5,160,100.0,NaN,2,39487,0,0,3,...,4.0,34,930147,9201,287008,59017,0.8,7.1,Pieters,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,0,0,0,NaN,NaN,0,104547,0,0,0,...,0.0,0,341,341,64,64,0.0,0.0,Gayle,0
272,0,0,0,0.0,0.0,0,84384,0,0,-1,...,0.0,0,475,14,4836,115,0.0,0.0,Klose,0
155,0,0,0,0.0,0.0,0,219352,0,0,0,...,0.0,0,88,5,463,10,0.0,0.0,Lookman,0
149,0,0,0,NaN,NaN,0,10318,0,0,0,...,0.0,0,156450,2522,107798,9372,0.0,0.0,Stekelenburg,0
145,0,0,0,100.0,100.0,0,12745,0,0,-1,...,0.0,0,4219,280,6761,399,0.0,0.0,Baines,0
539,0,0,0,NaN,NaN,0,173954,0,0,0,...,0.0,0,435,81,197,67,0.0,0.0,Riedewald,0
549,0,0,0,NaN,NaN,0,232937,0,0,0,...,0.0,0,6543,3404,1227,817,0.0,0.0,Williams,0
177,0,0,0,0.0,0.0,0,61604,0,0,-1,...,0.0,0,5875,36,17164,497,0.0,0.0,James,0
132,0,0,0,NaN,NaN,0,20066,0,0,-1,...,0.0,0,6533,336,32438,1453,0.0,0.0,Hennessey,0
178,0,0,0,100.0,100.0,0,155569,0,0,-1,...,0.0,0,8778,402,13851,796,0.0,0.0,Amartey,0
209,0,0,0,0.0,0.0,0,100180,0,0,0,...,0.0,0,350,22,5305,65,0.0,0.0,Danilo,0
216,0,0,0,0.0,0.0,0,182156,0,0,-2,...,0.0,0,1077,148,32131,358,0.0,0.0,Sané,0
550,0,0,0,0.0,NaN,0,444884,0,0,0,...,0.0,0,70,70,25,25,0.0,0.0,Elliott,0
531,0,0,0,NaN,NaN,0,200720,0,0,0,...,0.0,0,723,54,795,62,0.0,0.0,Kelleher,0
530,0,0,0,NaN,NaN,0,11948,0,0,-1,...,0.0,0,1999,39,2246,74,0.0,0.0,Lonergan,0
464,0,0,0,NaN,NaN,0,195473,0,0,-1,...,0.0,0,39138,2107,43498,2953,0.0,0.0,Brewster,0
440,0,0,14,NaN,NaN,0,145235,0,0,-3,...,2.0,0,2796,119,11866,340,0.0,0.0,Angeliño,1
201,0,0,0,0.0,0.0,0,217989,0,0,0,...,0.0,0,276,15,354,23,0.0,0.0,Camacho,0
196,0,0,0,100.0,100.0,0,175592,0,0,-2,...,0.0,0,2744,258,28433,317,0.0,0.0,Keita,0
223,0,0,0,0.0,0.0,0,55909,0,0,-2,...,0.0,0,1477,26,15220,217,0.0,0.0,Smalling,0
190,0,0,0,0.0,0.0,0,66797,0,0,0,...,0.0,0,293,9,2435,56,0.0,0.0,Mignolet,0
227,0,0,-2,NaN,NaN,0,58893,0,0,-2,...,4.0,0,2256,201,6998,375,0.0,0.0,Rojo,1
228,0,0,0,0.0,0.0,0,197365,0,0,-1,...,0.0,0,680,16,2325,44,0.0,0.0,Bailly,0
230,0,0,0,0.0,0.0,0,40002,0,0,-1,...,0.0,0,434,9,4358,94,0.0,0.0,Darmian,0
231,0,0,0,0.0,0.0,0,76359,0,0,-2,...,0.0,0,2188,33,9832,470,0.0,0.0,Jones,0
232,0,0,0,0.0,0.0,0,66749,0,0,0,...,0.0,0,925,51,28799,333,0.0,0.0,Lukaku,0
236,0,0,0,NaN,NaN,0,42899,0,0,-2,...,0.0,0,1803,1009,6108,302,0.0,0.0,Romero,0
237,0,0,0,NaN,NaN,0,6744,0,0,-1,...,0.0,0,338,65,3323,130,0.0,0.0,Grant,0
480,0,0,0,0.0,0.0,0,13152,0,0,-1,...,0.0,0,13132,59,36753,806,0.0,0.0,King,0
240,0,0,0,0.0,0.0,0,37265,0,0,-2,...,0.0,0,969,42,41190,482,0.0,0.0,Sánchez,0